version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - ng b --prod

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/angular-s3'
  discard-paths: no